package com.rbkmoney.jrekt8583;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.ToString;

@Getter
@ToString
@RequiredArgsConstructor
public enum MessageReasonCode {
    ICC_RANDOM_SELECTION("1502"),
    TERMINAL_RANDOM_SELECTION("1503"),
    ON_LINE_FORCED_BY_CARD_ACCEPTOR("1506"),
    ON_LINE_FORCED_BY_TERMINAL("1508"),
    ON_LINE_FORCED_BY_CARD_ISSUER("1509"),
    OVER_FLOOR_LIMIT("1510"),
    MERCHANT_SUSPICIOUS_MERCHANT_SUSPECTS_FRAUDULENT_CARD("1511"),
    CASHBACK_WITH_PURCHASE_ONLY_APPROVAL("1774"),
    REASON_CODE_IS_USED_AS_PARTIAL_APPROVAL_INDICATOR("1776"),
    PRECISION_INITIATIVE_TRANSACTION_IDENTIFICATION_INCREMENT("1777"),
    CUSTOMIZATION_FOR_SERVICE_PAYMENTS("1778"),
    VISA_MASTERCARD_APPLICATION_TRANSACTION_COUNTER("1779"),
    MASTERCARD_PAYMENT_ACCOUNT_STATUS_INQUIRY("1778"),
    AMEX_TRANSIT_ACCESS_TERMINAL_ACCOUNT_STATUS_CHECK("1780"),
    MASTER_CARD_MDES("1782"),
    RESUBMISSION_FOR_MNR_ON_ISSUING_DIRECTION_EXCLUSIVITY("1783"),
    DELAYED_CHARGES_FOR_MNR_ON_ISSUING_DIRECTION_EXCLUSIVITY("1784"),
    REAUTHORIZATION_FOR_MNR_ON_ISSUING_DIRECTION_EXCLUSIVITY("1785"),
    NO_SHOW_FOR_MNR_ON_ISSUING_DIRECTION_EXCLUSIVITY("1786"),
    ACCOUNT_TOP_UP_FOR_MNR_ON_ISSUING_DIRECTION_EXCLUSIVITY("1787"),
    CONSUMER_INITIATED_CIT_DEFERRED_AUTHORIZATION_CREDENTIAL_CAPTURED("1789"),
    PRE_AUTHORIZATIONS("1806"),
    PRE_AUTHORIZATIONS_WITH_PARTIAL_APPROVAL_REQUESTED_BY_MERCHANT("1818"),
    ISSUER_INSTALLMENT("1820"),
    MERCHANT_INSTALLMENT("1821"),
    ACQUIRER_INSTALMENT("1822"),
    VISA_U_S_MERCHANT_FINANCED_AUTHORIZATION_FOR_EACH_PAYMENT("1824"),
    BONUS_PURCHASE_1840("1840"),
    MASTERCARD_ACCOUNT_STATUS_INQUIRY_OR_VISA_STATUS_CHECK_OR_ACCOUNT_VERIFICATION("1900"),
    BONUS_PURCHASE_4502("4502"),
    SYSTEM_MALFUNCTION("4506"),
    FRAUD_ALERT_INDICATOR_FOR_ECOMMERCE("4514"),
    DECLINED_AUTHORIZATION("4522"),
    STAND_IN_PROCESSING_AT_CARD_ISSUERS_OPTION("1000"),
    CARD_ISSUER_TIMEOUT_DURING_ORIGINAL_REQUEST("1002"),
    TERMINAL_PROCESSED("1004"),
    ICC_PROCESSED("1005"),
    UNDER_FLOOR_LIMIT("1006"),
    STAND_IN_PROCESSING_AT_ACQUIRERS_OPTION("1007"),
    CUSTOMER_CANCELLATION("4000"),
    UNSPECIFIED_NO_ACTION_TAKEN("4001"),
    SUSPECTED_MALFUNCTION("4002"),
    FORMAT_ERROR_NO_ACTION_TAKEN("4003"),
    COMPLETED_PARTIALLY("4004"),
    ORIGINAL_AMOUNT_INCORRECT("4005"),
    RESPONSE_RECEIVED_TOO_LATE("4006"),
    CARD_ACCEPTOR_DEVICE_UNABLE_TO_COMPLETE_TRANSACTION("4007"),
    UNABLE_TO_DELIVER_MESSAGE_TO_POINT_OF_SERVICE("4013"),
    INVALID_RESPONSE_NO_ACTION_TAKEN("4020"),
    TIMEOUT_WAITING_FOR_RESPONSE("4021"),
    MALFUNCTION_NO_CASH_DISPENSED_AT_ATM("4017"),
    PRE_AUTHORIZATION_FULL_AND_PARTIAL_REVERSAL("1806");

    private final String code;
}
