package com.rbkmoney.jrekt8583.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum FunctionCode {
    ORIGINAL_AUTHORIZATION_AMOUNT_ACCURATE("100"),
    ORIGINAL_AUTHORIZATION_AMOUNT_ESTIMATED("101"),
    REPLACEMENT_AUTHORIZATION_AMOUNT_ACCURATE("102"),
    REPLACEMENT_AUTHORIZATION_AMOUNT_ESTIMATED("103"),
    SUPPLEMENTARY_AUTHORIZATION_AMOUNT_ESTIMATED("107"),
    INQUIRY("108"),
    ORIGINAL_FINANCIAL("200"),
    PREVIOUSLY_APPROVED_AUTHORIZATION_AMOUNT_SAME("201"),
    PREVIOUSLY_APPROVED_AUTHORIZATION_AMOUNT_DIFFERS("202"),
    DISPUTE_RESPONSE_FINANCIAL_STATUS_ADVICE("205"),
    DISPUTE_RESPONSE_FINANCIAL_REVERSAL_STATUS_ADVICE("205"),
    ACCOUNT_BASED_FINANCIAL_TRANSACTION("208"),
    CARD_STATUS_CHANGE_REQUEST("302"),
    CLIENT_INFORMATION_INQUIRY("305"),
    FULL_REVERSAL("400"),
    PARTIAL_REVERSAL("401"),
    DISPUTE_FINANCIAL_CHARGEBACK("450"),
    DISPUTE_FINANCIAL_CHARGEBACK_REVERSAL("480"),
    RECONCILIATION_REQUEST("500"),
    RECONCILIATION_ADVICE("500"),
    ACCOUNTS_LIST_REQUEST("689"),
    TOKENIZATION_NOTIFICATION("682"),
    PIN_CHANGE("690"),
    PIN_CHANGE_REVERSAL("690"),
    ADDENDUM_MESSAGES("699"),
    SIGN_ON("801"),
    SIGN_OFF("802"),
    ECHO_TEST("831");

    private final String code;
}
